### ISSUE TITLE
Bug with python3.7.3

### ISSUE THREAD

**Issue by cyrinux** [stamparm/identYwaf#11]
Hi,
I got this with my python 3.7.3, it's works well with python2

```
root@docker:~/toolbox/identifywaf$ python3 identYwaf.py --random-agent https://example.com                                    __ __ 
 ____  ___      ___  ____   ______ |  T  T __    __   ____  _____ 
l    j|   \    /  _]|    \ |      T|  |  ||  T__T  T /    T|   __|
 |  T |    \  /  [_ |  _  Yl_j  l_j|  ~  ||  |  |  |Y  o  ||  l_
 |  | |  D  YY    _]|  |  |  |  |  |___  ||  |  |  ||     ||   _|
 j  l |     ||   [_ |  |  |  |  |  |     ! \      / |  |  ||  ] 
|____jl_____jl_____jl__j__j  l__j  l____/   \_/\_/  l__j__jl__j  (1.0.119)

Traceback (most recent call last):
  File "identYwaf.py", line 581, in <module>
    main()
  File "identYwaf.py", line 574, in main
    init()
  File "identYwaf.py", line 362, in init
    print(colorize("[o] initializing handlers..."))
  File "/usr/lib/python3.7/codecs.py", line 378, in write
    self.stream.write(data)

TypeError: write() argument must be str, not bytes
```

**Comment by stamparm** [comment]
Thx
